# .github/ISSUE_TEMPLATE/bug.yml
name: "🐞 Bug Report"
description: A problem in the codebase causing incorrect behavior
title: "[Bug] "
labels: bug
body:
  - type: dropdown
    id: component
    attributes:
      label: Affected Component or Layer
      options:
        - Frontend
        - Backend
        - Agents
        - API
        - Data / DB
        - Infrastructure
        - CI/CD
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Environment or Version
      placeholder: staging, v1.5.0, commit abc123
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Button doesn't respond after login.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      placeholder: When user clicks 'Submit' on login, no response. Console shows 500 error.
    validations:
      required: true

  - type: input
    id: jira-ticket
    attributes:
      label: Jira Ticket (Optional)
      placeholder: e.g., LEXI-190
      description: Link to related Jira issue. Will auto-sync on creation.
    validations:
      required: false

  - type: input
    id: story-points
    attributes:
      label: Story Points (Optional)
      placeholder: "3"
      description: Effort estimate (e.g., 1, 2, 3, 5, 8)
    validations:
      required: false
      pattern: "^[0-9]+$"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, logs, or steps to reproduce.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Urgency / Priority
      options:
        - Low - Can wait
        - Medium - Should fix in next sprint
        - High - Blocking progress
        - Critical - Immediate attention needed
    validations:
      required: true
# EOF
