# .github/ISSUE_TEMPLATE/task.yml
name: "🧹 Task / Chore"
description: Non-feature work like cleanup or dependency updates
title: "[Task] "
labels: task
body:
  - type: dropdown
    id: component
    attributes:
      label: Affected Component or Layer
      options:
        - Frontend
        - Backend
        - Agents
        - API
        - Data / DB
        - Infrastructure
        - CI/CD
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Environment or Version
      placeholder: v1.5.0, main
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Upgrade React from 17 to 18.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      placeholder: Update dependencies, test for breaking changes, update docs.
    validations:
      required: true

  - type: input
    id: jira-ticket
    attributes:
      label: Jira Ticket (Optional)
      placeholder: e.g., LEXI-190
      description: Link to related Jira issue. Will auto-sync on creation.
    validations:
      required: false

  - type: input
    id: story-points
    attributes:
      label: Story Points (Optional)
      placeholder: 3
      description: Effort estimate (e.g., 1, 2, 3, 5, 8)
    validations:
      required: false
      pattern: "^[0-9]+$"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Link to changelog, migration guide, or related issue.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Urgency / Priority
      options:
        - Low - Can wait
        - Medium - Should fix in next sprint
        - High - Blocking progress
        - Critical - Immediate attention needed
    validations:
      required: true