# .github/workflows/stale.yml
name: Close Stale Issues & PRs
on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been inactive for 60 days. Please update or it will be closed.'
          close-issue-message: 'Closing due to inactivity.'
          stale-pr-message: 'This PR has been inactive for 30 days. Please update or it will be closed.'
          days-before-stale: 60
          days-before-close: 7
          exempt-issue-labels: pinned,security,release
          exempt-pr-labels: in-review,do-not-close,release
          operations-per-run: 100